config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'questions#index'

  resources :awards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy

  concern :rateable do
    member do
      patch :uprate
      patch :downrate
      delete :cancel
    end
  end

  resources :questions, only: %i[index show new create destroy update], shallow: true, concerns: :rateable do
    resources :comments, on: :member, only: :create, context: 'Question'

    resources :answers, only: %i[new create destroy update mark_as_best], concerns: :rateable do
      patch :mark_as_best, on: :member
      resources :comments, on: :member, only: :create, context: 'Answer'
    end
  end
end

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} errors present."
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_file.html.slim
.attachment id= file.id
  p= link_to file.filename.to_s, url_for(file)
  -if current_user&.author_of?(file.record)
    p= link_to 'X', attachment_path(file), method: :delete, remote: true

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :div, message

app/views/shared/_link.html.slim
li.attached-link id= link.id
  = link_to link.name, link.url
  -if current_user&.author_of?(link.linkable)
    = link_to "Delete", link_path(link), method: :delete, data: { confirm: 'Are you sure?' }, remote: true
  -if link.gist?
    = javascript_include_tag(link.url + '.js')

app/views/shared/_link_fields.html.slim
.nested-fields
  = f.label :name
  = f.text_field :name
  = f.label :url
  = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_rate.html.slim
.rate
  .rating id= "#{resource.class.to_s.downcase}-#{resource.id}"
    = resource.total_rating
  - if !current_user&.author_of?(resource) && user_signed_in?
    = link_to 'Uprate', polymorphic_path([:uprate, resource]), method: :patch, remote: true, data: { type: :json }
    = link_to 'Downrate', polymorphic_path([:downrate, resource]), method: :patch, remote: true, data: { type: :json }
    = link_to 'Cancel', polymorphic_path([:cancel, resource]), method: :delete, remote: true, data: { type: :json }