config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'questions#index'

  resources :awards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy

  concern :rateable do
    member do
      patch :uprate
      patch :downrate
      delete :cancel
    end
  end

  resources :questions, only: %i[index show new create destroy update], shallow: true, concerns: :rateable do
    resources :comments, on: :member, only: :create, context: 'Question'

    resources :answers, only: %i[new create destroy update mark_as_best], concerns: :rateable do
      patch :mark_as_best, on: :member
      resources :comments, on: :member, only: :create, context: 'Answer'
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Rateable
  include Commentable

  belongs_to :user
  belongs_to :question

  has_many :links, as: :linkable, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  scope :sort_by_best, -> { order(best: :desc) }

  def mark_as_best
    return if best == true

    transaction do
      self.class.where(question_id: question_id).update_all(best: false)
      update(best: true)
      question.award&.update!(user: user)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Rated

  before_action :authenticate_user!, except: :new
  before_action :set_question, only: %i[new create]
  before_action :set_answer, only: %i[update destroy mark_as_best]

  after_action :publish_answer, only: :create

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
    flash[:notice] = 'Answer was created successfully.'
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      flash[:notice] = 'Answer was deleted successfully.'
    else
      flash[:notice] = "You can't delete another's answer."
    end
  end

  def update
    if current_user.author_of?(@answer)
      @answer.update(answer_params)
      flash[:notice] = 'Answer was updated successfully.'
    else
      flash[:alert] = "You can't edit another's answer"
    end
  end

  def mark_as_best
    if current_user.author_of?(@answer.question)
      @answer.mark_as_best
      flash[:notice] = 'Best answer was chosen successfully!'
    else
      flash[:alert] = "You can't select the answer as best as a non-author!"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url _destroy])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast "question_channel_#{@answer.question.id}",
                                 html:
                                  ApplicationController.render(partial: 'answers/answer_ws',
                                                               locals: { answer: @answer }),
                                 author_id: current_user.id
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer.py-1 id= answer.id

  -if answer.best == true 
    p Best Answer
  p= answer.body
  
  = render 'shared/rate', resource: answer
  
  = render 'comments/form', commentable: answer

  -if answer.files.attached?
    = render partial: 'shared/file', collection: answer.files, as: :file

  -if answer.links.any?
    .attached-links
      p Links:
      ul
        = render partial: 'shared/link', collection: answer.links, as: :link

  .comments
    -if answer.comments.any?
      = render answer.comments

  -if current_user&.author_of?(answer) && answer.persisted?
    = link_to 'Delete', answer, method: :delete, remote: true, data: { confirm: 'Are you sure?' }
    = link_to 'Edit', '#', class: "edit-answer-link", data: { answer_id: answer.id }

    = form_with model: answer, local: false, class: 'd-none', id: "edit-answer-#{answer.id}" do |f|
      .form-group
      p
      = f.label :body
      = f.text_area :body
      p
      = f.label :files 
      = f.file_field :files, multiple: true, direct_upload: true

      .attachable-links
        = f.fields_for :links do |link|
        .links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      = f.submit "Save"
      
  -if current_user&.author_of?(answer.question) && answer.persisted?
    = link_to 'Mark As Best', mark_as_best_answer_path(answer), method: :patch, remote: true

app/views/answers/_answer_ws.html.slim
h3 New answer has been added!
p= answer.body

app/views/answers/create.js.erb
$('.flash').html('<%= render 'shared/flash' %>')
$('.answer-errors-creation').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html('<%= render 'shared/flash' %>')
$('div#<%= @answer.id %>.answer').remove()

app/views/answers/mark_as_best.js.erb
$('.flash').html('<%= render 'shared/flash' %>')
$('.answers').html('<%= j render @answer.question.answers.sort_by_best %>');

app/views/answers/new.html.slim
= render 'shared/errors', resource: @answer

app/views/answers/update.js.erb
$('.flash').html('<%= render 'shared/flash' %>')
$('.answer-errors-update').html('<%= render 'shared/errors', resource: @answer %>');
<% if !@answer.errors.present? %>
  $('div#<%= @answer.id %>.answer').replaceWith('<%= j render @answer %>');
<% end %>